INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (1, 'board', 'Board', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (2, 'card', 'Card', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (3, 'casual', 'Casual', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (4, 'family', 'Family', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (5, 'strategy', 'Strategy', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (6, 'adventure', 'Adventure', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (7, 'arcade', 'Arcade', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (8, 'bus', 'bus', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (9, 'driving', 'Driving', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (10, 'unity3d', 'Unity3D', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (11, 'webgl', 'WebGL', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (12, 'drawing', 'Drawing', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (13, 'best-games', 'Best Games', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (14, 'color', 'Color', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (15, 'puzzle', 'Puzzle', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (16, '1-player', '1 Player', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (17, '2048', '2048', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (18, '2d', '2D', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (19, 'air', 'Air', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (20, 'android', 'Android', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (21, 'bubble-shooter', 'Bubble Shooter', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (22, 'fight', 'Fight', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (23, '2-player', '2 Player', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (24, '2-player-games', '2 Player Games', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (25, 'action', 'Action', '', 1);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (26, 'animal', 'Animal', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (27, 'battle', 'Battle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (28, 'pixel', 'Pixel', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (29, 'cake', 'Cake', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (30, 'candy', 'Candy', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (31, 'girls', 'Girls', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (32, 'html5-games', 'html5 games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (33, 'jigsaw', 'Jigsaw', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (34, 'kids', 'Kids', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (35, 'mobile', 'Mobile', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (36, 'amazing', 'amazing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (37, 'fishing', 'Fishing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (38, 'fun', 'Fun', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (39, 'avoid', 'Avoid', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (40, 'boys', 'Boys', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (41, 'hypercasual', 'Hypercasual', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (42, 'jumping', 'Jumping', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (43, 'obstacle', 'Obstacle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (44, 'physics', 'Physics', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (45, 'free-html5-games-for-your-website', 'free html5 games for your website', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (46, 'stunts', 'Stunts', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (47, 'bomb', 'Bomb', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (48, 'castle', 'Castle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (49, 'classic', 'Classic', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (50, 'escape', 'Escape', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (51, 'fantasy', 'Fantasy', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (52, 'touchscreen', 'touchscreen', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (53, 'warrior', 'Warrior', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (54, 'educational', 'Educational', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (55, 'point-and-click', 'Point And Click', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (56, 'match-3', 'Match 3', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (57, 'match3', 'Match3', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (58, 'matching', 'Matching', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (59, 'math', 'Math', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (60, 'puzzleblock', 'puzzleblock', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (61, 'aircraft', 'Aircraft', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (62, 'airplane', 'airplane', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (63, 'shooting', 'Shooting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (64, 'tank', 'Tank', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (65, 'hidden', 'Hidden', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (66, 'running', 'running', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (67, 'bejeweled', 'Bejeweled', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (68, 'bicycle', 'Bicycle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (69, 'bullet', 'Bullet', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (70, 'clicker', 'Clicker', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (71, 'dragon', 'Dragon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (72, 'traffic', 'Traffic', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (73, 'ipad', 'iPad', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (74, 'iphone', 'iPhone', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (75, 'mentolatux', 'Mentolatux', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (76, 'race', 'Race', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (77, 'racing', 'Racing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (78, 'baby-games', 'Baby Games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (79, 'circus', 'circus', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (80, 'clash', 'Clash', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (81, 'collecting', 'Collecting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (82, 'logic', 'Logic', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (83, 'logical', 'Logical', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (84, 'onetouch', 'onetouch', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (85, 'monkey', 'Monkey', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (86, 'food', 'Food', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (87, 'fly', 'fly', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (88, 'highscore', 'Highscore', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (89, 'space', 'Space', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (90, 'spaceship', 'Spaceship', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (91, 'makeover', 'Makeover', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (92, 'nails', 'Nails', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (93, 'summer', 'Summer', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (94, 'super', 'Super', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (95, 'superhero', 'Superhero', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (96, '3d-games', '3D Games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (97, 'free-games-for-your-website', 'free games for your website', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (98, 'minecraft', 'Minecraft', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (99, 'funny', 'Funny', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (100, 'cars', 'Cars', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (101, 'gta', 'gta', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (102, 'transport', 'transport', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (103, 'bird', 'Bird', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (104, 'brain', 'Brain', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (105, 'cute', 'Cute', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (106, 'mineblock', 'mineblock', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (107, 'forest', 'Forest', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (108, 'jungle', 'jungle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (109, 'rescue', 'Rescue', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (110, 'timing', 'Timing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (111, 'room', 'Room', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (112, 'rabbit', 'Rabbit', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (113, 'doctor', 'Doctor', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (114, 'music', 'Music', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (115, 'attack', 'attack', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (116, 'fighting', 'Fighting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (117, 'impostor', 'Impostor', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (118, 'tower-defense', 'Tower Defense', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (119, 'survival', 'survival', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (120, 'zombie', 'Zombie', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (121, 'cook', 'Cook', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (122, 'sky', 'sky', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (123, 'interactive', 'Interactive', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (124, 'water', 'water', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (125, 'memory', 'Memory', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (126, 'skills', 'Skills', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (127, 'flight', 'Flight', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (128, 'naptech-games', 'NapTech Games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (129, 'online', 'Online', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (130, 'love', 'Love', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (131, 'cartoon', 'Cartoon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (132, 'cartoon-network', 'Cartoon Network', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (133, 'cooking', 'Cooking', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (134, 'crazy', 'Crazy', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (135, 'dress-up', 'Dress Up', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (136, 'fashion', 'Fashion', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (137, 'hair', 'Hair', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (138, 'school', 'School', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (139, 'balance', 'Balance', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (140, 'stickman', 'Stickman', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (141, 'magic', 'Magic', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (142, 'quiz', 'Quiz', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (143, 'spiderman', 'Spiderman', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (144, 'simulation', 'Simulation', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (145, 'cleaning', 'Cleaning', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (146, 'relaxation', 'Relaxation', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (147, 'maze', 'Maze', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (148, 'world', 'World', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (149, 'word', 'Word', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (150, 'endless', 'endless', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (151, 'free-games-for-your-site', 'free games for your site', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (152, 'mind', 'Mind', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (153, 'monster', 'Monster', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (154, 'rpg', 'RPG', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (155, 'snake', 'Snake', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (156, '8-ball-pool', '8 Ball Pool', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (157, 'billiard', 'Billiard', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (158, 'crash', 'crash', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (159, 'shoot-em-up', 'Shoot Em Up', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (160, 'army', 'Army', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (161, 'mountain', 'mountain', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (162, 'offroad', 'offroad', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (163, 'truck', 'Truck', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (164, 'trucks', 'trucks', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (165, 'panda', 'Panda', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (166, 'mouse', 'Mouse', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (167, 'halloween', 'Halloween', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (168, 'mapi-games', 'mapi games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (169, 'destroying', 'destroying', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (170, 'fire', 'Fire', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (171, 'sports', 'Sports', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (172, 'collection', 'Collection', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (173, 'house', 'House', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (174, 'kiz10', 'kiz10', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (175, 'lego', 'Lego', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (176, 'simulator', 'Simulator', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (177, 'coloring', 'Coloring', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (178, 'sort', 'sort', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (179, 'swipe', 'swipe', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (180, 'plant', 'Plant', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (181, 'arrows', 'arrows', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (182, 'military', 'military', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (183, 'platform', 'Platform', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (184, 'snow', 'Snow', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (185, 'top-down', 'Top Down', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (186, 'trap', 'trap', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (187, 'princess', 'Princess', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (188, 'city', 'city', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (189, 'decoration', 'Decoration', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (190, 'monstertruck', 'monstertruck', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (191, 'html5-games-for-your-site', 'html5 games for your site', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (192, 'robot', 'Robot', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (193, 'supercars', 'Supercars', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (194, 'fall-boys', 'Fall Boys', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (195, 'fall-guys', 'Fall Guys', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (196, 'bottle', 'bottle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (197, 'restaurant', 'Restaurant', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (198, 'mahjong', 'Mahjong', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (199, 'ballon', 'Ballon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (200, 'first-person-shooter', 'First Person Shooter', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (201, 'number', 'Number', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (202, 'parking', 'Parking', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (203, 'arena', 'Arena', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (204, 'gun', 'Gun', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (205, 'weapons', 'weapons', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (206, 'sorting', 'sorting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (207, 'planet', 'Planet', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (208, 'grow', 'grow', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (209, 'slide', 'slide', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (210, 'sword', 'Sword', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (211, 'boat', 'Boat', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (212, 'side-scrolling', 'Side Scrolling', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (213, 'multiplayer', 'Multiplayer', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (214, 'pvp', 'PvP', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (215, 'turn-based', 'Turn Based', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (216, 'two-player-games', 'two player games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (217, 'io-games', '.io Games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (218, 'battlegrounds', 'Battlegrounds', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (219, 'chicken', 'Chicken', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (220, 'kart', 'Kart', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (221, 'celebrity', 'Celebrity', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (222, 'frog', 'frog', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (223, 'carparking', 'carparking', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (224, 'bike', 'Bike', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (225, 'motorcycle', 'Motorcycle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (226, 'guessing', 'Guessing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (227, 'egg', 'egg', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (228, 'eggames', 'eggames', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (229, 'eggs', 'eggs', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (230, 'island', 'Island', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (231, 'rickshaw', 'Rickshaw', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (232, 'tuktuk', 'TukTuk', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (233, 'vehicle', 'vehicle', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (234, 'horror', 'Horror', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (235, 'pinball', 'Pinball', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (236, 'jelly', 'Jelly', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (237, 'ninja', 'Ninja', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (238, 'alien', 'Alien', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (239, 'baby-hazel', 'Baby Hazel', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (240, 'apocalypse', 'apocalypse', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (241, 'horse', 'Horse', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (242, 'slider', 'slider', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (243, 'waterslide', 'waterslide', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (244, 'car-tuning', 'car tuning', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (245, 'spongebob', 'Spongebob', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (246, 'hunter', 'hunter', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (247, 'lion', 'lion', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (248, 'eating', 'eating', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (249, 'build', 'build', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (250, 'builder', 'builder', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (251, 'building', 'building', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (252, 'assassin', 'assassin', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (253, 'assasin', 'assasin', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (254, 'throwing', 'throwing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (255, 'football', 'Football', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (256, 'letters', 'Letters', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (257, 'difference', 'Difference', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (258, 'angryplants', 'angryplants', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (259, 'blockchain', 'blockchain', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (260, 'fruit', 'Fruit', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (261, 'fruits', 'Fruits', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (262, 'smash', 'smash', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (263, 'shopping', 'Shopping', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (264, 'mermaid', 'Mermaid', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (265, 'miner', 'Miner', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (266, 'dungeon', 'Dungeon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (267, 'mario', 'Mario', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (268, 'wizard', 'Wizard', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (269, 'angrybirds', 'angrybirds', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (270, 'huggy', 'huggy', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (271, 'penguin', 'Penguin', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (272, 'bounce', 'Bounce', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (273, 'drifting', 'drifting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (274, 'dinosaur', 'Dinosaur', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (275, 'wolf', 'Wolf', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (276, 'design', 'Design', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (277, 'html-games-for-your-website', 'html games for your website', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (278, 'bridge', 'Bridge', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (279, 'management', 'Management', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (280, 'soccer', 'Soccer', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (281, 'unity-games-for-your-website', 'unity games for your website', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (282, 'adult', 'Adult', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (283, 'battleship', 'battleship', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (284, 'arkanoid', 'Arkanoid', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (285, 'bricks', 'Bricks', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (286, 'atv', 'atv', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (287, 'sandbox', 'Sandbox', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (288, 'enemies', 'Enemies', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (289, 'hello-kitty', 'Hello Kitty', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (290, 'blocky', 'blocky', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (291, 'science', 'Science', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (292, 'anime', 'Anime', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (293, 'crafting', 'Crafting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (294, 'friv', 'Friv', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (295, 'watermelon', 'watermelon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (296, 'level', 'Level', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (297, 'levels', 'Levels', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (298, 'police', 'Police', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (299, 'street-fighting', 'Street Fighting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (300, 'taxi', 'Taxi', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (301, 'tractor', 'tractor', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (302, 'tetris', 'Tetris', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (303, 'knight', 'Knight', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (304, 'barbie', 'Barbie', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (305, 'fps', 'fps', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (306, 'world-of-alice', 'World of Alice', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (307, 'prison', 'Prison', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (308, 'casino', 'Casino', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (309, 'basketball', 'Basketball', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (310, 'holiday', 'Holiday', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (311, 'golf', 'Golf', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (312, 'grimace', 'Grimace', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (313, 'grimace-shake', 'Grimace Shake', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (314, 'gambling', 'gambling', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (315, 'poker', 'Poker', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (316, 'ships', 'ships', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (317, 'bmx', 'BMX', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (318, 'buggy', 'buggy', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (319, 'rocket', 'Rocket', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (320, 'pacman', 'PacMan', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (321, 'helicopter', 'Helicopter', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (322, 'retro', 'Retro', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (323, 'skateboard', 'Skateboard', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (324, 'csgo', 'CSGO', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (325, 'enemy', 'Enemy', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (326, 'hot', 'Hot', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (327, 'burger', 'Burger', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (328, 'business', 'Business', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (329, 'motocross', 'Motocross', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (330, 'farm', 'Farm', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (331, 'launch', 'Launch', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (332, 'tanks', 'Tanks', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (333, 'gold', 'Gold', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (334, 'cool', 'Cool', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (335, 'new', 'New', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (336, 'pirate', 'Pirate', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (337, 'subway', 'subway', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (338, 'subway-surfers', 'Subway Surfers', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (339, 'sound', 'sound', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (340, 'ambulance', 'ambulance', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (341, 'chair', 'chair', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (342, 'wheel', 'wheel', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (343, 'ladybug', 'Ladybug', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (344, 'destruction', 'destruction', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (345, 'hex', 'hex', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (346, 'spin-wheel', 'spin-wheel', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (347, 'surprise', 'surprise', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (348, 'surprize', 'surprize', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (349, 'solitaire', 'Solitaire', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (350, 'shark', 'Shark', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (351, 'slither', 'Slither', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (352, 'worms', 'Worms', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (353, 'easter', 'Easter', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (354, 'polygon', 'Polygon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (355, 'wheels', 'wheels', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (356, 'detective', 'Detective', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (357, 'hunting', 'Hunting', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (358, 'pokemon', 'Pokemon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (359, 'disney', 'Disney', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (360, 'elsa', 'Elsa', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (361, 'winter', 'Winter', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (362, 'hockey', 'hockey', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (363, 'samurai', 'Samurai', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (364, 'pomni', 'Pomni', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (365, 'sumo', 'sumo', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (366, 'sneak', 'sneak', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (367, 'freezenova', 'FreezeNova', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (368, 'onlinegames-io', 'onlinegames io', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (369, 'skibidi', 'Skibidi', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (370, 'skibidi-toilet', 'Skibidi Toilet', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (371, 'unity-games-for-your-site', 'unity games for your site', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (372, 'vampire', 'Vampire', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (373, 'sniper', 'Sniper', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (374, 'boxing', 'Boxing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (375, 'miraculous-ladybug', 'Miraculous Ladybug', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (376, 'zuma', 'Zuma', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (377, 'dora', 'Dora', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (378, 'santa', 'Santa', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (379, 'yoga', 'Yoga', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (380, 'slot-machine', 'Slot Machine', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (381, 'decorate', 'Decorate', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (382, 'blackjack', 'blackjack', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (383, 'cannon', 'cannon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (384, 'dash', 'dash', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (385, 'skating', 'Skating', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (386, 'digital-circus', 'digital circus', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (387, 'surgery', 'Surgery', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (388, 'steal', 'steal', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (389, 'thief', 'Thief', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (390, 'bow', 'Bow', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (391, 'geometry', 'Geometry', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (392, 'hexa', 'hexa', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (393, 'hexagon', 'hexagon', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (394, 'h5', 'H5', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (395, 'valentine', 'valentine', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (396, 'valentine-day', 'valentine day', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (397, 'valentines', 'valentines', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (398, 'ghost', 'Ghost', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (399, 'helix', 'Helix', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (400, 'stack', 'Stack', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (401, 'grooming', 'Grooming', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (402, 'pipe', 'Pipe', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (403, 'santa-claus', 'Santa Claus', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (404, 'frozen', 'Frozen', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (405, 'christmas', 'Christmas', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (406, 'typing', 'Typing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (407, 'brawl', 'Brawl', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (408, 'dancing', 'Dancing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (409, 'witch', 'Witch', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (410, 'slicing', 'Slicing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (411, 'red', 'Red', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (412, 'undead', 'Undead', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (413, 'kiss', 'Kiss', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (414, 'kissing', 'Kissing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (415, 'onlyup', 'OnlyUp', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (416, 'demolition', 'demolition', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (417, 'creation', 'Creation', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (418, 'movie', 'Movie', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (419, 'batman', 'Batman', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (420, 'train', 'Train', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (421, 'clans', 'Clans', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (422, 'minion', 'Minion', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (423, 'submachine', 'Submachine', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (424, 'baseball', 'Baseball', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (425, 'punch', 'Punch', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (426, 'killing', 'Killing', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (427, 'goat', 'goat', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (428, 'blood', 'Blood', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (429, 'dragon-ball-z', 'Dragon Ball Z', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (430, 'bmx-games', 'BMX Games', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (431, 'pony', 'Pony', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (432, 'dating', 'Dating', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (433, 'ben-10', 'Ben 10', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (434, 'google', 'Google', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (435, 'trial-car', 'trial car', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (436, 'seduction', 'Seduction', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (437, 'silver', 'Silver', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (438, 'tennis', 'Tennis', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (439, 'mmo', 'MMO', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (440, 'rhythm', 'Rhythm', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (441, 'stealth', 'Stealth', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (442, 'interactive-fiction', 'Interactive Fiction', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (443, 'ninjago', 'Ninjago', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (444, 'fairy', 'Fairy', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (445, 'kiz-10', 'Kiz 10', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (446, 'violence', 'Violence', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (447, 'tomb', 'tomb', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (448, 'ever-after-high', 'Ever After High', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (449, 'sofia', 'Sofia', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (450, 'simpson', 'Simpson', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (451, 'whack', 'Whack', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (452, 'slacking', 'Slacking', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (453, 'sudoku', 'Sudoku', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (454, 'temple', 'temple', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (455, 'pou', 'Pou', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (456, 'roblox', 'roblox', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (457, 'sliding', 'sliding', '', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (458, 'gamedistribution', 'gamedistribution', 'gamedistribution', 0);
INSERT INTO "tags" ("id", "slug", "name", "description", "featured") VALUES (459, 'sprunki', 'Sprunki', '', 0);
